(display "Test 1: Basic string literal")
(newline)
(display "  => (define hw \"hello, world!\")")
(newline)
(define hw "hello, world!")
(display "  Result: ")
(display hw)
(newline)
(newline)


(display "Test 2: string? predicate")
(newline)
(display "  => (string? \"I am a string\")")
(newline)
(display "  Result: ")
(display (string? "I am a string"))
(newline)

(display "  => (string? 12345)")
(newline)
(display "  Result: ")
(display (string? 12345))
(newline)
(newline)


(display "Test 3: string-length")
(newline)
(display "  => (string-length \"hello\")")
(newline)
(display "  Result: ")
(display (string-length "hello"))
(newline)

(display "  => (string-length \"\")")
(newline)
(display "  Result: ")
(display (string-length ""))
(newline)
(newline)


(display "Test 4: string-append")
(newline)
(display "  => (string-append \"hello\" \" \" \"world\")")
(newline)
(display "  Result: ")
(display (string-append "hello" " " "world"))
(newline)

(display "  => (string-append hw \" -- from a variable\")")
(newline)
(display "  Result: ")
(display (string-append hw " -- from a variable"))
(newline)
(newline)


(display "Test 5: Escape sequences")
(newline)
(define escapes "Line 1\nLine 2\twith a tab and a \\ backslash and a \" quote.")
(display "  => (define escapes \"Line 1\\nLine 2\\twith a tab and a \\\\ backslash and a \\\" quote.\")")
(newline)
(display "  Result (should be on multiple lines):")
(newline)
(display escapes)
(newline)
(display "  Length of escape string (should be 58): ")
(display (string-length escapes))
(newline)
(newline)


(display "Test 6: Using strings with functions")
(newline)
(define (greet name)
  (string-append "Hello, " name "!"))
(display "  => (define (greet name) (string-append \"Hello, \" name \"!\"))")
(newline)
(display "  => (greet \"Alice\")")
(newline)
(display "  Result: ")
(display (greet "Alice"))
(newline)
